name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - master  # Or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy by building on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_WEB }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_WEB }}
          script: |
            set -e

            # Clone repository if not already cloned
            if [ ! -d ~/my-react-app ]; then
              git clone https://github.com/jai-Mp-ro-one/Padmashali-Website.git ~/my-react-app
            fi

            cd ~/my-react-app
            git fetch origin
            git reset --hard origin/master

            # Install dependencies and build React app
            npm ci
            npm run build

            echo "Build folder contents:"
            ls -lah build

            # Clean Nginx web root and copy build files
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r build/. /usr/share/nginx/html/

            # Set ownership and permissions for Nginx running as ubuntu
            sudo chown -R ubuntu:ubuntu /usr/share/nginx/html
            sudo find /usr/share/nginx/html -type d -exec chmod 755 {} \;
            sudo find /usr/share/nginx/html -type f -exec chmod 644 {} \;

            # Reload nginx to serve the new content
            sudo systemctl reload nginx